<Workspace Version="0.8.2.2392" X="406" Y="198" zoom="1" Name="DetailLine w LineStyle.ByCurve in Active View" Description="Create Detail Line w LineStyle by a Curve in the Active Revit View" ID="9c13cf4f-8ec1-4714-8def-91e04c51bb6b" Category="BCJdt.Graphics">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="beb8ac24-c577-4b02-9092-bf35ae813095" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script># Copyright(c) 2015, Jon Szczesniak - @jonszcz
# BCJdt - Bohlin Cywinski Jackson designtech

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSTType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)


# --- INPUTS ---
#The inputs to this node will be stored as a list in the IN variables.
#The location Curves will be stored in the IN[0] variable.
_locCurves = UnwrapElement(IN[0])

#The intended LineStyle Output will be stored in the IN[1] variable.
_linestyle = UnwrapElement(IN[1])

doc = DocumentManager.Instance.CurrentDBDocument
app = DocumentManager.Instance.CurrentUIApplication.Application

# --- OUTPUTS ---
outCurve = []
# --- BODY ---

#Transaction - Use when creating content in the Revit Model
TransactionManager.Instance.EnsureInTransaction(doc)
# Iterate through the location Curves and draw a Revit Detail line based on those Curves
for c in _locCurves:
	detCurve = doc.Create.NewDetailCurve(doc.ActiveView, c.ToRevitType())
	detCurve.LineStyle = _linestyle
	outCurve.append(detCurve)
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = outCurve</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol guid="aa93c5c7-ec2c-4af2-bcd0-154ebc977d2e" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Curves" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="d63a18d4-d808-4768-92de-cc872ac10686" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="GraphicStyle" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="7b9b0dc9-76a8-44ad-aace-3ea290de3124" type="Dynamo.Nodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Detail Lines" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="beb8ac24-c577-4b02-9092-bf35ae813095" start_index="0" end="7b9b0dc9-76a8-44ad-aace-3ea290de3124" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="aa93c5c7-ec2c-4af2-bcd0-154ebc977d2e" start_index="0" end="beb8ac24-c577-4b02-9092-bf35ae813095" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d63a18d4-d808-4768-92de-cc872ac10686" start_index="0" end="beb8ac24-c577-4b02-9092-bf35ae813095" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="40.7218742370605" eyeY="56.4510650634766" eyeZ="99.4931335449219" lookX="-41.9661903381348" lookY="-62.7990951538086" lookZ="-86.0434417724609" />
  </Cameras>
</Workspace>